config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("spam/", include("spam.urls", namespace="spam")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spam/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from spam.apps import SpamConfig
from spam.views import (
    BlockMailingView,
    HomePageView,
    MailingAttemptListView,
    MailingClearAttemptsView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingStartView,
    MailingUpdateView,
    MessageCreateView,
    MessageDeleteView,
    MessageDetailView,
    MessageListView,
    MessageUpdateView,
    RecipientCreateView,
    RecipientDeleteView,
    RecipientDetailView,
    RecipientListView,
    RecipientUpdateView,
    UserMailingStatisticsView,
)

app_name = SpamConfig.name


urlpatterns = [
    path("home/", HomePageView.as_view(), name="home"),
    path("message_list/", cache_page(30)(MessageListView.as_view()), name="message_list"),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/update", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("message/<int:pk>/detail/", MessageDetailView.as_view(), name="message_detail"),
    path("recipient/<int:pk>/", RecipientDetailView.as_view(), name="recipient_detail"),
    path("recipient/", cache_page(30)(RecipientListView.as_view()), name="recipient_list"),
    path("recipient_form/", RecipientCreateView.as_view(), name="recipient_form"),
    path(
        "recipient/update/<int:pk>/",
        RecipientUpdateView.as_view(),
        name="recipient_update",
    ),
    path(
        "recipient/<int:pk>/delete",
        RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path("mailing_list/", cache_page(30)(MailingListView.as_view()), name="mailing_list"),
    path("mailing_create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/update", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path(
        "mailing_attempt_list/",
        MailingAttemptListView.as_view(),
        name="mailing_attempt_list",
    ),
    path(
        "mailing/<int:mailing_id>/start/",
        MailingStartView.as_view(),
        name="mailing_start",
    ),
    path(
        "clear-mailing-attempts/",
        MailingClearAttemptsView.as_view(),
        name="clear_mailing_attempts",
    ),
    path("user/statistics/", UserMailingStatisticsView.as_view(), name="user_statistics"),
    path(
        "mailing/<int:mailing_id>/block/",
        BlockMailingView.as_view(),
        name="mailing_block",
    ),
]

spam/models.py
import logging

from config import settings
from django.core.mail import BadHeaderError, send_mail
from django.db import models
from django.utils import timezone
from users.models import CustomUser
from utils.logger import setup_logging

setup_logging()


class Recipient(models.Model):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=255)
    comment = models.TextField(blank=True)
    owner = models.ForeignKey(
        CustomUser,
        verbose_name="Владелец",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"
        ordering = ["full_name"]
        permissions = [
            ("can_view_all_recipients", "can view all recipients"),
        ]


class Message(models.Model):
    subject = models.CharField(max_length=255)
    body = models.TextField()
    owner = models.ForeignKey(
        CustomUser,
        verbose_name="Владелец",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["subject"]
        permissions = [
            ("can_view_all_messages", "can view all messages"),
        ]


class Mailing(models.Model):
    STATUS_CHOICES = [
        ("Создана", "Создана"),
        ("Запущена", "Запущена"),
        ("Завершена", "Завершена"),
    ]

    first_send_time = models.DateTimeField(null=True, blank=True, help_text="укажите время в формате 2023-10-01 12:00")
    end_time = models.DateTimeField(null=True, blank=True, help_text="укажите время в формате 2023-10-01 12:00")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="Создана")
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    recipients = models.ManyToManyField(Recipient)
    owner = models.ForeignKey(
        CustomUser,
        verbose_name="Владелец",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        return f"Рассылка {self.pk} - {self.status}"

    def send_mailing(self):
        """Отправка сообщений всем получателям и логирование попыток отправки"""
        user_stats, created = UserMailingStatistics.objects.get_or_create(user=self.owner)
        if self.is_blocked:
            logging.info(f"Рассылка {self.pk} заблокирована.")
            return

        if self.status != "Создана":
            logging.info(f"Начало выполнения задачи: {self.status}")
            return

        if self.status != "Запущена":
            self.status = "Запущена"
            self.start_datetime = timezone.now()
            self.save()

            recipients = self.recipients.all()
            success_count = 0
            for recipient in recipients:
                logging.info(f"Начало выполнения задачи: {recipient.email}")
                try:
                    send_mail(
                        subject=self.message.subject,
                        message=self.message.body,
                        from_email=settings.EMAIL_HOST_USER,
                        recipient_list=[recipient.email],
                        fail_silently=False,
                    )

                    MailingAttempt.objects.create(
                        mailing=self,
                        status="Успешно",
                        server_response="Письмо отправлено успешно.",
                        attempt_datetime=timezone.now(),
                    )

                    success_count += 1
                    user_stats.update_statistics(success=True)

                except BadHeaderError as e:
                    logging.error(f"Ошибка отправки письма: {e}")
                    MailingAttempt.objects.create(
                        mailing=self,
                        status="Не успешно",
                        server_response=str(e),
                        attempt_datetime=timezone.now(),
                    )
                    user_stats.update_statistics(success=False)

                except Exception as e:
                    logging.error(f"Ошибка отправки письма: {e}")
                    MailingAttempt.objects.create(
                        mailing=self,
                        status="Не успешно",
                        server_response=str(e),
                        attempt_datetime=timezone.now(),
                    )
                    user_stats.update_statistics(success=False)

            if success_count == len(recipients):
                self.status = "Завершена"
            self.save()

    def block_mailing(self):
        self.is_blocked = True
        self.save()
        logging.info(f"Рассылка {self.pk} заблокирована пользователем {self.owner}")

    def unblock_mailing(self):
        self.is_blocked = False
        self.save()
        logging.info(f"Рассылка {self.pk} разблокирована пользователем {self.owner}")

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        permissions = [
            ("can_view_all_mailings", "can view all mailings"),
            ("can_disable_mailings", "can disable mailings"),
        ]


class MailingAttempt(models.Model):
    ATTEMPT_STATUS_CHOICES = [
        ("Успешно", "Успешно"),
        ("Не успешно", "Не успешно"),
    ]

    attempt_datetime = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=ATTEMPT_STATUS_CHOICES)
    server_response = models.TextField(blank=True)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    owner = models.ForeignKey(
        CustomUser,
        verbose_name="Владелец",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f"Попытка: {self.status} at {self.attempt_datetime}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытка рассылок"
        permissions = [
            ("can_view_all_mailings_attempts", "can view all mailings attempts"),
        ]


class UserMailingStatistics(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    total_mailings = models.PositiveIntegerField(default=0)
    successful_mailings = models.PositiveIntegerField(default=0)
    failed_mailings = models.PositiveIntegerField(default=0)

    def update_statistics(self, success):
        self.total_mailings += 1
        if success:
            self.successful_mailings += 1
        else:
            self.failed_mailings += 1
        self.save()

spam/forms.py
from django import forms

from .models import Mailing, Message, Recipient


class RecipientForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields = ["email", "full_name", "comment"]


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["subject", "body"]

    def clean(self):
        cleaned_data = super().clean()
        subject = cleaned_data.get("subject")
        body = cleaned_data.get("body")

        if subject.lower() and body.lower() in [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]:
            self.add_error("subject", "запрещенное слово")
            self.add_error("body", "запрещенное слово")


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ["first_send_time", "end_time", "message", "recipients", "status"]
        widgets = {
            "start_time": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "end_time": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }

spam/templates/spam/mailing_attempt_list.html
{% extends "spam/base.html" %}

{% block title %}Список попыток рассылок{% endblock %}

{% block content %}
<h2>Список попыток рассылок</h2>

<form action="{% url 'spam:clear_mailing_attempts' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Очистить список рассылок</button>
</form>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Рассылка</th>
            <th>Время попытки</th>
            <th>Статус</th>
            <th>Ответ сервера</th>
            <th>Сообщение</th>
            <th>Получатели</th>
        </tr>
    </thead>
    <tbody>

        {% for attempt in mailing_attempt_list %}
            {% if user == attempt.owner or user.is_staff or perms.spam.can_view_all_mailings_attempts %}
                <tr>
                    <td>
                        <a href="{% url 'spam:mailing_detail' attempt.mailing.id %}">
                             Рассылка №: {{ attempt.mailing.id }}
                        </a>
                    </td>
                    <td>{{ attempt.attempt_datetime|date:"d.m.Y H:i:s" }}</td>
                    <td>{{ attempt.status }}</td>
                    <td>{{ attempt.server_response|default:"Нет ответа" }}</td>
                    <td>{{ attempt.mailing.message.body }}</td>
                    <td>
                    {% for recipient in attempt.mailing.recipients.all %}
                        {{ recipient.email }}<br>
                    {% endfor %}
                    </td>
                </tr>
            {% endif %}
        {% empty %}
            <tr>
                <td colspan="6">Нет записей о попытках рассылки.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

spam/templates/spam/mailing_block.html
{% extends 'spam/base.html' %}
{% block title %} Блокировка рассылки {% endblock %}
{% block content %}
<div class="container mt-5">

    <h1 class="mb-4">
        {% if mailing.is_blocked %}
            Разблокировать рассылку
        {% else %}
            Заблокировать рассылку
        {% endif %}
    </h1>
    <p>Вы уверены, что хотите {% if mailing.is_blocked %}разблокировать{% else %}
        заблокировать{% endif %} рассылку "{{ mailing.id }}"?</p>

    <form method="post">
        {% csrf_token %}
        <input type="checkbox" name="is_blocked" id="id_is_blocked" {% if mailing.is_blocked %}checked{% endif %}>
        <label for="id_is_blocked">
            {% if mailing.is_blocked %}
                Разблокировать рассылку
            {% else %}
                Заблокировать рассылку
            {% endif %}
        </label>
        <button type="submit" class="btn btn-primary">
            {% if mailing.is_blocked %}
                Разблокировать
            {% else %}
                Заблокировать
            {% endif %}
        </button>
        <a href="{% url 'spam:mailing_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

spam/templates/spam/mailing_delete.html
{% extends 'spam/base.html'%}

{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Удалить сообщение </h1>
        <p>Вы уверены, что хотите удалить "{{ object.id }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" > Удалить</button>
            <a href="{% url 'spam:message_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

spam/templates/spam/mailing_detail.html
{% extends "spam/base.html" %}
{% block title %} Подробности рассылки {% endblock %}

{% block content %}
    <h1>Рассылка №{{ mailing.id }}</h1>
    <table>
    {% if user == mailing.owner or user.is_staff or perms.spam.can_view_all_mailings%}
        <tr>
            <th>Дата и Время Первой Отправки</th>
            <td>{{ mailing.first_send_time }}</td>

                <td>
                    {% if user == mailing.owner or user.is_staff %}
                        <a href="{% url 'spam:mailing_update' mailing.id %}">Редактировать</a>
                        <a href="{% url 'spam:mailing_delete' mailing.id %}">Удалить</a>
                    {% endif %}
                    {% if perms.spam.can_disable_mailings or user.is_staff %}
                    {% if mailing.is_blocked %}
                        <td><a href="{% url 'spam:mailing_block' mailing.id %}">Разблокировать рассылку</a></td>
                    {% else %}
                        <td><a href="{% url 'spam:mailing_block' mailing.id %}">Заблокировать рассылку</a></td>
                    {% endif %}
                    {% endif %}
                </td>

        </tr>

        <tr>
            <th>Дата и Время Окончания Отправки</th>
            <td>{{  mailing.end_time }}</td>
        </tr>
        <tr>
            <th>Статус</th>
            <td>{{ mailing.status }}</td>

        </tr>
        <tr>
            <th>Сообщение</th>
            <td>{{ mailing.message|truncatewords:100 }}</td>
        </tr>
        <tr>
            <th>Получатели</th>
            <td>
                <ul>
                {% for recipient in mailing.recipients.all %}
                    <li>{{ recipient.full_name }} ({{ recipient.email }})</li>
                {% endfor %}
                </ul>
            </td>

        </tr>
    {% endif %}
    </table>
{% endblock %}

spam/templates/spam/mailing_form.html
{% extends "spam/base.html" %}

{% block title %}{{ "Добавление рассылок" }}{% endblock %}

{% block content %}
<h2>{{ "Создание рассылки" }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'spam:mailing_list' %}">Назад к списку рассылок</a>
{% endblock %}

spam/templates/spam/mailing_list.html
{% extends "spam/base.html" %}
{% block title %} Рассылки {% endblock %}

{% block content %}
    <h1>Список рассылок</h1>
    <a href="{% url 'spam:mailing_create' %}">Добавить рассылку</a>

    <table>

        {% for mailing in mailing_list %}
            {% if user == mailing.owner or user.is_staff or perms.spam.can_view_all_mailings %}
            <tr>
                <td>
                    <a href="{% url 'spam:mailing_detail' mailing.id %}">
                         Рассылка №: {{ mailing.id }} Подробнее
                    </a>
                </td>
            </tr>
            <tr>
                <th>Владелец рассылки</th>
                <td>
                    {{ mailing.owner }}
                </td>
            </tr>
            <tr>

                <th>Дата и Время Первой Отправки</th>
                <td>{{ mailing.first_send_time }}</td>
                {% if user == mailing.owner or user.is_staff %}
                <td>
                    <a href="{% url 'spam:mailing_start' mailing.id %}">Начать рассылку</a>
                </td>
                {% endif %}
            </tr>

            <tr>
                <th>Дата и Время Окончания Отправки</th>
                <td>{{ mailing.end_time }}</td>
            </tr>
            <tr>
                <th>Статус</th>
                <td>{{ mailing.status }}</td>
            </tr>
            <tr>
                <th>Сообщение</th>
                <td>{{ mailing.message|truncatewords:100 }}</td>
            </tr>
            <tr>
                <th>Получатели</th>
                <td>
                    <ul>
                    {% for recipient in mailing.recipients.all %}
                        <li>{{ recipient.full_name }} ({{ recipient.email }})</li>
                    {% endfor %}
                    </ul>
                </td>
            </tr>



            <tr>
                <th>Статус рассылки</th>
                <td>
                    {% if mailing.is_blocked %}
                        Заблокировано
                    {% else %}
                        Разблокировано
                    {% endif %}
                </td>
            </tr>
        {% endif %}
        {% endfor %}
    </table>
{% endblock %}

spam/templates/spam/mailing_start.html
{% extends "spam/base.html" %}

{% block title %}Начало рассылки{% endblock %}

{% block content %}
    <h1>Начать рассылку</h1>
    <p>Вы уверены, что хотите начать рассылку "{{ mailing.object.id }}"?</p>

    <form method="post" action="{% url 'spam:mailing_start' object.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Начать рассылку</button>
    </form>
    <a href="{% url 'spam:mailing_list' %}">Назад к списку рассылок</a>
{% endblock %}

spam/templates/spam/message_delete.html
{% extends 'spam/base.html'%}

{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Удалить сообщение </h1>
        <p>Вы уверены, что хотите удалить "{{ object.subject }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" > Удалить</button>
            <a href="{% url 'spam:message_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

spam/templates/spam/message_detail.html
{% extends "spam/base.html" %}

{% block title %}Сообщения{% endblock %}

{% block content %}
<h2>Сообщения</h2>
<a href="{% url 'spam:message_create' %}">Добавить сообщение</a>
<table>
    <tr>
        <th> Тема сообщения </th>
        <th> Тело сообщения </th>
        <th> Подробнее о сообщении</th>
    </tr>
        {% if user == message.owner or user.is_staff or perms.spam.can_view_all_messages %}
            <tr>
                <td>{{ message.subject }}</td>
                <td>{{ message.body|truncatewords:100 }}</td>
                <td><a class="btn btn-outline-primary" href="{% url 'spam:message_list' %}">Назад</a></td>
            </tr>
        {% endif %}

</table>
{% endblock %}>

spam/templates/spam/message_from.html
{% extends "spam/base.html" %}

{% block title %}{{ " Добавление сообщения " }}{% endblock %}

{% block content %}
<h2>{{ "Редактирование сообщения" }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'spam:message_list' %}">Назад к списку сообщений</a>
{% endblock %}

spam/templates/spam/message_list.html
{% extends "spam/base.html" %}

{% block title %}Сообщения{% endblock %}

{% block content %}
<h2>Сообщения</h2>
<a href="{% url 'spam:message_create' %}">Добавить сообщение</a>
<table>
    <tr>
        <th> Тема сообщения </th>
        <th> Тело сообщения </th>
        <th> Подробнее о сообщении</th>
    </tr>
    {% for message in message_list %}
        {% if user == message.owner or user.is_staff or perms.spam.can_view_all_messages %}
            <tr>
                <td>{{ message.subject }}</td>
                <td>{{ message.body|truncatewords:100 }}</td>
                <td><a class="btn btn-outline-primary" href="{% url 'spam:message_detail' message.id %}">
                    Подробнее
                </a></td>
            </tr>
        {% endif %}
    {% endfor %}
</table>
{% endblock %}>

spam/templates/spam/recipient_delete.html
{% extends 'spam/base.html'%}

{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Удалить получателя </h1>
        <p>Вы уверены, что хотите удалить "{{ message.subject }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" > Удалить</button>
            <a href="{% url 'spam:recipient_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

spam/templates/spam/recipient_detail.html
{% extends "spam/base.html" %}
{% block title %}Получатель рассылки{% endblock %}

{% block content %}
<h2>Получатель рассылки</h2>
<table>
    <div class="container">
      <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
        <div class="col">
          <div class="p-3 border bg-light">Email</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">Ф. И. О.</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">Комментарий</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">Редактировать</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">Удалить</div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
        <div class="col">
          <div class="p-3 border bg-light">{{ recipient.email }}</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">{{ recipient.full_name }}</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light">{{ recipient.comment }}</div>
        </div>
        {% if user == recipient.owner or user.is_staff or perms.user.delete_recipient %}
        <div class="col">
          <div class="p-3 border bg-light"><a href="{% url 'spam:recipient_update' recipient.id %}">Редактировать</a></div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light"><a href="{% url 'spam:recipient_delete' recipient.id %}">Удалить</a></div>
        </div>
        {% endif %}
      </div>
    </div>

</table>
{% endblock %}

spam/templates/spam/recipient_form.html
{% extends "spam/base.html" %}

{% block title %}{{ form.instance.id|yesno:"Редактирование получателя,Добавление получателя" }}{% endblock %}

{% block content %}
<h2>{{ form.instance.id|yesno:"Редактирование получателя,Добавление получателя" }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'spam:recipient_list' %}">Назад к списку получателей</a>
{% endblock %}>