config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("spam/", include("spam.urls", namespace="spam")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spam/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from spam.apps import SpamConfig
from spam.views import (
    BlockMailingView,
    HomePageView,
    MailingAttemptListView,
    MailingClearAttemptsView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingListView,
    MailingStartView,
    MailingUpdateView,
    MessageCreateView,
    MessageDeleteView,
    MessageDetailView,
    MessageListView,
    MessageUpdateView,
    RecipientCreateView,
    RecipientDeleteView,
    RecipientDetailView,
    RecipientListView,
    RecipientUpdateView,
    UserMailingStatisticsView,
)

app_name = SpamConfig.name


urlpatterns = [
    path("home/", HomePageView.as_view(), name="home"),
    path("message_list/", cache_page(30)(MessageListView.as_view()), name="message_list"),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/update", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("message/<int:pk>/detail/", MessageDetailView.as_view(), name="message_detail"),
    path("recipient/<int:pk>/", RecipientDetailView.as_view(), name="recipient_detail"),
    path("recipient/", cache_page(30)(RecipientListView.as_view()), name="recipient_list"),
    path("recipient_form/", RecipientCreateView.as_view(), name="recipient_form"),
    path(
        "recipient/update/<int:pk>/",
        RecipientUpdateView.as_view(),
        name="recipient_update",
    ),
    path(
        "recipient/<int:pk>/delete",
        RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path("mailing_list/", cache_page(30)(MailingListView.as_view()), name="mailing_list"),
    path("mailing_create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/update", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path(
        "mailing_attempt_list/",
        MailingAttemptListView.as_view(),
        name="mailing_attempt_list",
    ),
    path(
        "mailing/<int:mailing_id>/start/",
        MailingStartView.as_view(),
        name="mailing_start",
    ),
    path(
        "clear-mailing-attempts/",
        MailingClearAttemptsView.as_view(),
        name="clear_mailing_attempts",
    ),
    path("user/statistics/", UserMailingStatisticsView.as_view(), name="user_statistics"),
    path(
        "mailing/<int:mailing_id>/block/",
        BlockMailingView.as_view(),
        name="mailing_block",
    ),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (
    BlockUserView,
    ChangePasswordView,
    ConfirmEmailView,
    PasswordResetView,
    RegisterView,
    UserDetailView,
    UserListView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="spam:home"), name="logout"),
    path(
        "confirm-email/<str:user_email>/",
        ConfirmEmailView.as_view(),
        name="confirm_email",
    ),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("user_block/<int:user_id>", BlockUserView.as_view(), name="user_block"),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("profile/<int:pk>", UserDetailView.as_view(), name="user_profile"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    username = models.CharField(max_length=50, verbose_name="username", help_text="Введите имя пользователя")
    email = models.EmailField(unique=True, verbose_name="Email", help_text="Введите свой email")
    phone_number = models.CharField(
        max_length=15,
        verbose_name="Телефон",
        blank=True,
        null=True,
        help_text="Введите номер телефона",
    )
    avatar = models.ImageField(
        upload_to="photo/avatar",
        blank=True,
        null=True,
        verbose_name="Аватар",
        help_text="Загрузите аватар",
    )
    country = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name="Страна",
        help_text="Укажите страну",
    )
    is_blocked = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ["email"]
        permissions = [
            ("can_manage_users", "can manage users"),
            ("can_block_users", "can block users"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import CustomUser


class RegisterUserCreationForm(UserCreationForm):
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        help_text="Необязательное поле для ввода. " "Введите ваш номер телефона.",
    )
    username = forms.CharField(max_length=50, required=True)

    class Meta:
        model = CustomUser
        fields = (
            "email",
            "username",
            "avatar",
            "first_name",
            "phone_number",
            "password1",
            "password2",
            "country",
        )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        first_name = cleaned_data.get("first_name")

        if username.lower() and first_name.lower() in [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]:
            self.add_error("username", "запрещенное слово")
            self.add_error("first_name", "запрещенное слово")

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        if phone_number and not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен состоять только из цифр")
        return phone_number

    def clean_avatar(self):
        cleaned_data = super().clean()
        avatar = cleaned_data.get("image")

        if avatar is None:
            return None

        if avatar.size > 5 * 1024 * 1024:
            raise forms.ValidationError("Размер файла не должен превышать 5MB.")

        if not avatar.name.endswith(("jpg", "jpeg", "png")):
            raise forms.ValidationError(
                "Формат файла не соответствует требованиям. " "Формат файла должен быть *.jpg, *.jpeg, *.png"
            )

        return avatar


class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = [
            "email",
            "username",
            "avatar",
            "first_name",
            "phone_number",
            "country",
        ]
        exclude = (
            "is_blocked",
            "owner",
        )

users/views.py
import random
import string

from config.settings import EMAIL_HOST_USER
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from users.forms import RegisterUserCreationForm
from users.models import CustomUser


class RegisterView(CreateView):
    form_class = RegisterUserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("spam:home")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.send_welcome_email(user.email)
        return super().form_valid(form)

    def send_welcome_email(self, user_email):
        subject = "Добро пожаловать в наш сервис"
        activation_link = f"http://127.0.0.1:8000/users/confirm-email/{user_email}/"
        message = (
            f"Спасибо, что зарегистрировались в нашем сервисе!\n\n "
            f"Пожалуйста, подтвердите ваш адрес электронной почты, перейдя по следующей ссылке:\n "
            f"{activation_link}\n\n "
            f"Мы рады видеть вас среди наших пользователей."
        )
        from_email = settings.EMAIL_HOST_USER
        recipient_list = [user_email]
        send_mail(subject, message, from_email, recipient_list)


class ConfirmEmailView(View):
    def get(self, request, user_email):
        user = get_object_or_404(CustomUser, email=user_email)

        if user.is_active:
            return HttpResponse("Ваш адрес электронной почты уже подтвержден!")

        user.is_active = True
        user.save()
        return HttpResponse("Ваш адрес электронной почты был подтвержден!")


class UserListView(ListView):
    model = CustomUser
    template_name = "users/user_list.html"
    context_object_name = "user_list"

    def get_queryset(self):
        return CustomUser.objects.all()


class UserDetailView(DetailView):
    model = CustomUser
    template_name = "users/user_profile.html"
    context_object_name = "user_profile"


class BlockUserView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(CustomUser, id=user_id)
        return render(request, "users/user_block.html", {"user": user})

    def post(self, request, user_id):
        user = get_object_or_404(CustomUser, id=user_id)

        if not request.user.has_perm("users.can_block_users"):
            return HttpResponseForbidden("У вас нет прав для блокировки рассылки.")

        is_blocked = request.POST.get("is_blocked")
        user.is_blocked = is_blocked == "on"
        user.save()
        return redirect("users:user_list")


class PasswordResetView(View):
    def get(self, request):
        return render(request, "users/password_reset.html")

    def post(self, request):
        email = request.POST.get("email")
        try:
            user = CustomUser.objects.get(email=email)
            new_password = "".join(random.choices(string.ascii_letters + string.digits, k=8))
            user.password = make_password(new_password)
            user.save()
            send_mail(
                subject="Ваш новый пароль",
                message=f"Здравствуйте!\nВаш новый пароль: {new_password}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
            messages.success(request, "Новый пароль отправлен на ваш email.")
            return redirect("users:login")
        except CustomUser.DoesNotExist:
            messages.error(request, "Пользователь с таким email не найден.")
            return render(request, "users/password_reset.html")


class ChangePasswordView(LoginRequiredMixin, View):
    def get(self, request):
        form = PasswordChangeForm(user=request.user)
        return render(request, "users/change_password.html", {"form": form})

    def post(self, request):
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)

            send_mail(
                subject="Ваш пароль был изменен",
                message=f"Здравствуйте, {user.username}!\n\nВаш пароль был успешно изменен.",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )

            messages.success(request, "Ваш пароль был успешно изменен!")
            return redirect("users:change_password")

        messages.error(request, "Пожалуйста, исправьте ошибки в форме.")
        return render(request, "users/change_password.html", {"form": form})

users/templates/users/change_password.html
{% extends "spam/base.html" %}
{% block title %} Изменение пароля пользователя {% endblock %}
{% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    <h2>Изменить пароль</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="p-2 btn btn-outline-success"  type="submit">Изменить пароль</button>
    </form>
    <a class="p-2 btn btn-outline-primary"  href="{% url 'users:user_profile' user.id %}">Назад к профилю</a>
{% endblock %}

users/templates/users/login.html
{% extends 'spam/base.html'%}
{% block content %}
<div class="container mt-5">
    <h1>Вход на сайт</h1>
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Войти</button>
                    </div>
                </div>
            </div>
        </form>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'spam/base.html' %}
{% block title %} Восстановление пароля {% endblock %}
{% block content %}
<div class="container mt-5">
    <h1>Восстановление пароля</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Восстановить пароль</button>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'spam/base.html'%}
{% block title %} Регистрация {% endblock %}
{% block content %}
<div class="container mt-5">
    <h1>Регистрация</h1>
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Регистрация</button>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="container mt-5">
    <h1>Восстановление пароля</h1>
    <a href="{% url 'users:password_reset' %}" class="btn btn-link">Восстановить пароль</a>
</div>
{% endblock %}

users/templates/users/user_block.html
{% extends 'spam/base.html' %}
{% block title %} Блокировка пользователя {% endblock %}
{% block content %}
<div class="container mt-5">

    <h1 class="mb-4">
        {% if user.is_blocked %}
            Разблокировать пользователя
        {% else %}
            Заблокировать пользователя
        {% endif %}
    </h1>
    <p>Вы уверены, что хотите {% if user.is_blocked %}разблокировать{% else %}заблокировать{% endif %} пользователя "{{ user.email }}"?</p>

    <form method="post">
        {% csrf_token %}
        <input type="checkbox" name="is_blocked" id="id_is_blocked" {% if user.is_blocked %}checked{% endif %}>
        <label for="id_is_blocked">
            {% if user.is_blocked %}
                Разблокировать пользователя
            {% else %}
                Заблокировать пользователя
            {% endif %}
        </label>
        <button type="submit" class="btn btn-primary">
            {% if user.is_blocked %}
                Разблокировать
            {% else %}
                Заблокировать
            {% endif %}
        </button>
        <a href="{% url 'users:user_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends "spam/base.html" %}
{% load my_tags %}
{% block title %}Получатель рассылки{% endblock %}
{% block content %}
<h2>Список пользоваелей</h2>
<table class="table">
    <thead>
        <tr>
            <th>Email</th>
            <th>Ф. И. О.</th>
            <th>Nikcname</th>
            <th>Телефон</th>
            <th>Аватар</th>
            <th>Страна</th>
            <th>Статус</th>

        </tr>
    </thead>
    <tbody>
        {% for user in user_list %}
            {% if perms.users.can_manage_users and not user.is_superuser %}
            <tr>
                <td>{{ user.email }}</td>
                <td>{{ user.first_name }} {{user.last_name}}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.phone_number }}</td>
                <td><img src="{{ user.avatar | media_filter }}" class="card-img-top" alt="avatar"
                         style="max-width: 150px; max-height: 150px; width: auto; height: auto;"></td>
                <td>{{ user.country }}</td>
                <td>
                    {% if user.is_blocked %}
                        Заблокировано
                    {% else %}
                        Разблокировано
                    {% endif %}
                </td>
                {% if perms.users.can_block_users or user.is_staff %}
                {% if user.is_blocked %}
                    <td><a href="{% url 'users:user_block' user.id %}">Разблокировать пользователя</a></td>
                {% else %}
                    <td><a href="{% url 'users:user_block' user.id %}">Заблокировать пользователя</a></td>
                {% endif %}
                {% endif %}
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'spam/base.html' %}
{% load my_tags %}
{% block content %}
<h1>Детали пользователя: {{ user.username }}</h1>

<div class="user-details">
    <img src="{{ user.avatar | media_filter }}" class="card-img-top" alt="avatar"
         style="max-width: 150px; max-height: 150px; width: auto; height: auto;">

    <ul>
    <li><strong>Email:</strong> {{ user.email }}</li>
    <li><strong>Имя:</strong> {{ user.first_name }}</li>
    <li><strong>Номер телефона:</strong> {{ user.phone_number }}</li>
    <li><strong>Страна:</strong> {{ user.country }}</li>
    </ul>
    <div class="card">
        <div class="card-body">
            <a class="btn btn-primary" href="{% url 'users:change_password' %}">Изменить пароль</a>
        </div>
    </div>
</div>

{% endblock %}